# Site settings
title: Karl Persson
description: Programmer // Geek

facebook: http://facebook.com/gaffeln/
twitter: https://twitter.com/GaffelGaffel
googleplus: https://plus.google.com/104666399294253485125/about
linkedin: https://www.linkedin.com/pub/karl-persson/92/791/b22
lastfm: http://www.lastfm.se/user/GaffelGaffel
github: https://github.com/GaffelGaffel

# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: assets/css
    style: :nested