# Site settings
title: Karl Persson
description: Programmer // Geek

# About
about: <p><strong>Bacon ipsum</strong> dolor sit amet shoulder swine cupidatat irure bresaola proident sint dolore shankle nostrud. Hamburger id deserunt bacon aliqua, tongue porchetta non nostrud short ribs frankfurter ea. Commodo dolore brisket ball tip.</p>

# Contact
facebook: http://facebook.com/gaffeln/
twitter: https://twitter.com/GaffelGaffel
googleplus: https://plus.google.com/104666399294253485125/about
linkedin: https://www.linkedin.com/pub/karl-persson/92/791/b22
lastfm: http://www.lastfm.se/user/GaffelGaffel
github: https://github.com/GaffelGaffel

# Footer
fork-me: https://github.com/GaffelGaffel/gaffelgaffel.github.io
name: Karl Persson
year: 2014

# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: assets/css
    style: :nested